[test]
# Ignore these folders during testing and module resolution
pathIgnorePatterns = [
  "engine262/**",
  "spec-built/**",
  "node_modules/**",
  "dist/**",
  "build/**",
  "coverage/**",
  ".idea/**",
  "docs/**",
  "storage/**",
  "graphology/**",
  ".git/**",
]
